<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MicrosoftToDoEnhanced</RootNamespace>
		<AssemblyName>MicrosoftToDoEnhanced</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\General\General.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="General.Models" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
	</ItemGroup>

</Project>