<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MicrosoftToDoEnhanced</RootNamespace>
		<AssemblyName>MicrosoftToDoEnhanced</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\General\General.csproj" />
	</ItemGroup>

</Project>