<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\General\General.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="General.Models" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="SQL\CreateDatabase.txt" />
  </ItemGroup>

</Project>
